#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use CanalTP\PHPGit\Command\TagCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new TagCommand);
$application->run();
